spring.application.name=energy-app

# Configurazione del databese MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/energy_app
spring.datasource.username=root
spring.datasource.password=root

# Crea ed elimina automaticamente lo schema del database e usa il dialect MySQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mostra le query SQL in console e formatta l'output per renderlo leggibile
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Proprietà JWT: dato che sono custom segnala -> PROP_UNKNOWN_PROPERTY
# ma Spring Boot le utlizzerà comunque grazie a @Value("${jwt.secret}"), ecc.
jwt.secret=my-super-secret-key
jwt.issuer=auth0-demo
jwt.expiration-ms=3600000